name: "Check PR Checklist"

on:
  pull_request:
    types: [opened, edited]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR body contains completed checklist
        run: |
          echo "PR Body: ${{ github.event.pull_request.body }}"
          if ! grep -q "\- \[x\]" "${{ github.event.pull_request.body }}"; then
            echo "Checklist is not complete. Please complete the checklist before merging."
            exit 1
          fi
