name: "Check PR Checklist"

on:
  pull_request:
    types: [opened, edited]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR body contains completed checklist
        run: |
          echo "${{ github.event.pull_request.body }}" | grep -q -E '^\s*-\s+\[x\]' 
          if [ $? -ne 0 ]; then
            echo "Checklist is not complete. Please complete the checklist before merging."
            exit 1
          else
            echo "Checklist complete."
          fi
